import { useContext } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { AppBar, Container, IconButton, makeStyles, Toolbar, Typography, useScrollTrigger } from '@material-ui/core';
import { ThemeContext } from '../src/theme';

const useStyles = makeStyles(theme => ({
  root: {
    flexGrow: 1
  },
  appBar: {
    boxShadow: "none",
  }
}))

export default function Home() {

  const classes = useStyles();

  const { toggleTheme, isDark } = useContext(ThemeContext)

  const trigger = useScrollTrigger({ disableHysteresis: true })
  return (
    <div className={classes.root}>
      <Head>
        <title>Murali Devan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar color={!trigger ? "transparent" : "inherit"} className={classes.appBar} position="fixed" >
        <Toolbar>
          <Typography variant="h6" className={classes.root}>
            Murali Devan
          </Typography>
          <IconButton edge="end" color="inherit" onClick={toggleTheme}>
            {isDark ? "☀️" : "🌑"}
          </IconButton>
        </Toolbar>
      </AppBar>
      <Toolbar className={classes.toolbar} />



    </div>
  )
}
